### ISSUE TITLE
.DS_Store

### ISSUE THREAD

**Issue by Naprogramuji** [yairm210/Unciv-mod-example#2]
Tomas-Triska-MacBook-Pro:unciv TomasTriska$ java -jar Unciv.jar
Exception in thread "main" java.lang.RuntimeException: Error packing images.
	at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:657)
	at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:644)
	at com.unciv.app.desktop.DesktopLauncher.packImages(DesktopLauncher.kt:64)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:22)
Caused by: java.lang.IllegalArgumentException: Input file does not exist: /Applications/Unciv/mods/.DS_Store/Images
	at com.badlogic.gdx.tools.FileProcessor.process(FileProcessor.java:118)
	at com.badlogic.gdx.tools.texturepacker.TexturePackerFileProcessor.process(TexturePackerFileProcessor.java:84)
	at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:655)
	... 3 more
Tomas-Triska-MacBook-Pro:unciv TomasTriska$

**Comment by rh-github-2015** [comment]
Should be fixed with [Unciv#2211](https://github.com/yairm210/Unciv/pull/2211)
